name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment: dev
      
    permissions:
      contents: 'read'
      id-token: 'write'  # Needed for OIDC

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/1078754960579/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
        service_account: "github-deployer@sigma-healthsense.iam.gserviceaccount.com"

    - name: Set up gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Build & push Docker image
      run: |
        IMAGE=gcr.io/sigma-healthsense/hospital-eye-backend:$GITHUB_SHA
        gcloud builds submit --tag $IMAGE .
        echo "IMAGE=$IMAGE" >> $GITHUB_ENV

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy hospital-eye-backend \
          --image ${{ env.IMAGE }} \
          --platform managed \
          --region us-central1 \
          --allow-unauthenticated \
          --set-env-vars MONGODB_URI=${{ secrets.MONGODB_URI }},
                GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }},
                GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},
                GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},
                FRONTEND_BASE_URL=${{ secrets.FRONTEND_BASE_URL }},
                JWT_SECRET=${{ secrets.JWT_SECRET }},
                NODE_ENV=${{ secrets.NODE_ENV }}