name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - dev

permissions:
  contents: read
  id-token: write  

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: development

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Remove old creds
        run: rm -f gha-creds-*.json || true

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          workload_identity_provider: projects/1078754960579/locations/global/workloadIdentityPools/github-pool/providers/github-provider
          service_account: github-deployer@sigma-healthsense.iam.gserviceaccount.com
          audience: https://token.actions.githubusercontent.com

      - name: Set GCP Project
        run: gcloud config set project ${{ secrets.PROJECT_ID }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker ${{ secrets.REGION }}-docker.pkg.dev --quiet

      - name: Build and Push Docker Image
        run: |
          IMAGE="${{ secrets.REGION }}-docker.pkg.dev/${{ secrets.PROJECT_ID }}/backend-dev-repo/${{ secrets.SERVICE_NAME }}:${{ github.sha }}"
          docker build -t "$IMAGE" .
          docker push "$IMAGE"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy ${{ secrets.SERVICE_NAME }} \
            --image $IMAGE \
            --region ${{ secrets.REGION }} \
            --platform managed \
            --service-account ${{ secrets.SERVICE_ACCOUNT_EMAIL }} \
            --set-env-vars "MONGODB_URI=${{ secrets.MONGODB_URI }},
                            JWT_SECRET=${{ secrets.JWT_SECRET }},
                            GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }},
                            GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }},
                            GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }},
                            FRONTEND_BASE_URL=${{ secrets.FRONTEND_BASE_URL }},
                            NODE_ENV=${{ secrets.NODE_ENV }}"
